// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(FlightSystemContext))]
    [Migration("20241023161114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entity.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("API.Entity.Flight", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightID"));

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsFlightCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("PointOfLoading")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PointOfUnloading")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalDocuments")
                        .HasColumnType("int");

                    b.HasKey("FlightID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("API.Entity.FlightDocument", b =>
                {
                    b.Property<int>("FlightDocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightDocumentID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<int>("FlightID")
                        .HasColumnType("int");

                    b.HasKey("FlightDocumentID");

                    b.HasIndex("DocumentID");

                    b.HasIndex("FlightID");

                    b.ToTable("FlightDocuments");
                });

            modelBuilder.Entity("API.Entity.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionID"));

                    b.Property<bool>("CanDownload")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<bool>("NoPermission")
                        .HasColumnType("bit");

                    b.Property<int>("PermissionGroupID")
                        .HasColumnType("int");

                    b.HasKey("PermissionID");

                    b.HasIndex("DocumentID");

                    b.HasIndex("PermissionGroupID");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("API.Entity.PermissionGroup", b =>
                {
                    b.Property<int>("PermissionGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionGroupID"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionGroupID");

                    b.ToTable("PermissionGroups");

                    b.HasData(
                        new
                        {
                            PermissionGroupID = 1,
                            GroupName = "Admin"
                        },
                        new
                        {
                            PermissionGroupID = 2,
                            GroupName = "Back-Office"
                        },
                        new
                        {
                            PermissionGroupID = 3,
                            GroupName = "Pilot"
                        },
                        new
                        {
                            PermissionGroupID = 4,
                            GroupName = "Crew"
                        });
                });

            modelBuilder.Entity("API.Entity.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(2024, 10, 23, 23, 11, 13, 590, DateTimeKind.Local).AddTicks(2846),
                            Email = "admin@vietjetair.com",
                            FullName = "Admin User",
                            PasswordHash = "$2a$11$CN4fKGg0smrKagOUYCnTaunpqbBayRG/yq1K/spt5mtheKJolhwzq",
                            RefreshToken = "1d3afffd-c52e-4a85-8ecf-2a10356d6855",
                            RefreshTokenExpiryTime = new DateTime(2024, 10, 30, 23, 11, 13, 702, DateTimeKind.Local).AddTicks(8108),
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedAt = new DateTime(2024, 10, 23, 23, 11, 13, 702, DateTimeKind.Local).AddTicks(8134),
                            Email = "backoffice@vietjetair.com",
                            FullName = "BackOffice User",
                            PasswordHash = "$2a$11$0PO5V3JuZKXntFJAT4Nj4uREHUbp3KlnVReiohh9wt3FcfI7nM4wq",
                            RefreshToken = "4f688d0c-105c-47a2-b438-1c302dc8805c",
                            RefreshTokenExpiryTime = new DateTime(2024, 10, 30, 23, 11, 13, 815, DateTimeKind.Local).AddTicks(9683),
                            Role = "Back-Office",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = 3,
                            CreatedAt = new DateTime(2024, 10, 23, 23, 11, 13, 815, DateTimeKind.Local).AddTicks(9708),
                            Email = "pilot@vietjetair.com",
                            FullName = "Pilot User",
                            PasswordHash = "$2a$11$KZ5E63uqLBXcqdaaCWMhgOHooCD.AY2w5rZMdA5ipVXWhNwM7fPha",
                            RefreshToken = "e4b5f807-2c08-4ef6-9778-54455732b715",
                            RefreshTokenExpiryTime = new DateTime(2024, 10, 30, 23, 11, 13, 931, DateTimeKind.Local).AddTicks(959),
                            Role = "Pilot",
                            Status = "Active"
                        },
                        new
                        {
                            UserID = 4,
                            CreatedAt = new DateTime(2024, 10, 23, 23, 11, 13, 931, DateTimeKind.Local).AddTicks(996),
                            Email = "crew@vietjetair.com",
                            FullName = "Crew User",
                            PasswordHash = "$2a$11$8CMphSrSFZ5Q3qCeoLtmv.hfx4lGwp.EPfMs2EyWU6m6bfETup6vO",
                            RefreshToken = "0136e748-3d53-4435-9e94-0715fc4b5bdd",
                            RefreshTokenExpiryTime = new DateTime(2024, 10, 30, 23, 11, 14, 43, DateTimeKind.Local).AddTicks(9969),
                            Role = "Crew",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("API.Entity.FlightDocument", b =>
                {
                    b.HasOne("API.Entity.Document", "Document")
                        .WithMany("FlightDocuments")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entity.Flight", "Flight")
                        .WithMany("FlightDocuments")
                        .HasForeignKey("FlightID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("API.Entity.Permission", b =>
                {
                    b.HasOne("API.Entity.Document", "Document")
                        .WithMany("Permissions")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entity.PermissionGroup", "PermissionGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("PermissionGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("API.Entity.Document", b =>
                {
                    b.Navigation("FlightDocuments");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("API.Entity.Flight", b =>
                {
                    b.Navigation("FlightDocuments");
                });

            modelBuilder.Entity("API.Entity.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
